# Generated by Django 2.0.2 on 2018-03-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='hash_value',
        ),
        migrations.AddField(
            model_name='url',
            name='short_url',
            field=models.CharField(default='bit.ly/', max_length=8, unique=True),
        ),
    ]
